import sharp from "sharp";
import { mkdirSync, writeFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const outDir = join(__dirname, "..", "public", "icons");
mkdirSync(outDir, { recursive: true });

const FOREST = "#173f32";
const CREAM = "#fff7ec";
const ORANGE = "#e96b2c";

// Reuses the "wrap" glyph from components/ui/FoodIcons.tsx (64x64 viewBox)
// as the app's brand mark, so the installed icon matches the in-app icon
// language instead of introducing a second, unrelated logo.
const WRAP_GLYPH = `
  <path d="M14 20c0-6 8-10 18-10s18 4 18 10-14 30-18 30-18-24-18-30Z" fill="${CREAM}" fill-opacity="0.15" stroke="${CREAM}" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" />
  <path d="M14 20c0-6 8-10 18-10s18 4 18 10" fill="none" stroke="${CREAM}" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" />
  <path d="M17 24c4 2 26 2 30 0M15 30c6 2 28 2 34 0M18 38c4 1.5 20 1.5 24 0" fill="none" stroke="${CREAM}" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" />
  <circle cx="32" cy="20" r="3" fill="${ORANGE}" />
`;

function iconSvg({ canvas, glyphSize, background }) {
  const offset = (canvas - glyphSize) / 2;
  return `
    <svg width="${canvas}" height="${canvas}" viewBox="0 0 ${canvas} ${canvas}" xmlns="http://www.w3.org/2000/svg">
      ${background ? `<rect width="${canvas}" height="${canvas}" fill="${FOREST}"/>` : ""}
      <svg x="${offset}" y="${offset}" width="${glyphSize}" height="${glyphSize}" viewBox="0 0 64 64">
        ${WRAP_GLYPH}
      </svg>
    </svg>
  `;
}

async function writePng(filename, svg, size) {
  await sharp(Buffer.from(svg)).resize(size, size).png().toFile(join(outDir, filename));
  console.log(`wrote ${filename}`);
}

const tasks = [
  // "any" purpose icons: glyph fills most of the canvas, background included.
  { filename: "icon-192.png", size: 192, canvas: 192, glyphSize: 132, background: true },
  { filename: "icon-512.png", size: 512, canvas: 512, glyphSize: 352, background: true },
  { filename: "apple-touch-icon.png", size: 180, canvas: 180, glyphSize: 124, background: true },
  // maskable: keep the glyph inside the ~80% safe zone so OS masking never clips it.
  { filename: "icon-maskable-512.png", size: 512, canvas: 512, glyphSize: 256, background: true },
];

for (const t of tasks) {
  const svg = iconSvg(t);
  await writePng(t.filename, svg, t.size);
}

writeFileSync(
  join(outDir, "README.md"),
  "Generated by scripts/generate-icons.mjs — do not hand-edit. Re-run the script to regenerate after changing the glyph or brand colors.\n"
);
